spring:
  application:
    name: pedidosapi
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidos
    username: postgres1
    password: postgres1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true